ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "taash"
  site-url: "https://nasheqlbrm.github.io/taash"
  description: "A deck of cards demo of [nbdev](https://nbdev.fast.ai)"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/nasheqlbrm/taash"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/nasheqlbrm/taash"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
